feat(Dockerfile): install git toolchain in `bitnami/kubectl` (#43)
`kubectl` binary also include `kustomize` to build configurable
manifest.
`kubectl kustomize` supports three options: "no flag", "directory" and
"url".

The official documentation show the following example:
```
kubectl kustomize "https://github.com/kubernetes-sigs/kustomize.git/exam
ples/helloWorld?ref=v1.0.6"
```

But it does not work with `bitnami/kubectl:latest`

```
docker run --rm bitnami/kubectl:latest kustomize "https://github.com/
kubernetes-sigs/kustomize.git/examples/helloWorld?ref=v1.0.6"
error: no 'git' program on path: exec: "git": executable file not found
in $PATH
```

The problem is that it requires `git` to pull the repository and
execute it.
This commit include `git-all` in the installed package to solve this
issue.

Signed-off-by: Vasek - Tom C <tom.chauveau@epitech.eu>